name: NimohSurvival
version: '1.2-Alpha'
main: src.net.jadiefication.survival.Survival
api-version: '1.21'
bootstrapper: src.net.jadiefication.Bootstrap.Bootstrap
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    Essentials:
      load: BEFORE
      required: true
    BetterTeams:
      load: BEFORE
      required: true
